### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by myungdae** [jonphipps/Metadata-Registry#34]
Hi there,

I want to create some **rdf vocabularies** for our purposes. I want to register it here on Open Metadata Registry. I saw sandbox stuff, but I don't know where can I start if I really want to register. 

Maybe I missed that part, but at the moment I can't find it. Please help me in this regard ^^

With Many Thanks,

**Myungdae Cho**

Professor
Seoul National University

**Comment by jonphipps** [comment]
Apologies for the delay in responding...

It's probably best to stay away from the sandbox -- we'll be taking that down soon and migrating the work people have done there to private projects on the OMR, if they wish.

There are instructions here: http://wiki.metadataregistry.org/Open_Metadata_Registry_Step-By-Step_Instruction

They haven't been updated to reflect the most recent changes, especially to import and export of vocabularies via CSV file, but should get you started. The OMR is under heavy development at the moment and the documentation hasn't caught up with reality yet.

If you have more questions, please feel free to ask them on our [gitter channel](https://gitter.im/jonphipps/Metadata-Registry)
